package com.sinognss.cloud.vantix.common.exception;

public enum ErrorCode {
    INVALID_ARGUMENT("INVALID_ARGUMENT"),
    NOT_FOUND("NOT_FOUND"),
    COMPANY_RELATION_INVALID("COMPANY_RELATION_INVALID"),
    SERVICE_CODE_EXPIRED("SERVICE_CODE_EXPIRED"),
    SERVICE_CODE_NOT_PENDING("SERVICE_CODE_NOT_PENDING"),
    SERVICE_CODE_NOT_OWNED("SERVICE_CODE_NOT_OWNED"),
    TRANSFER_NOT_ALLOWED("TRANSFER_NOT_ALLOWED"),
    BATCH_STATUS_INCONSISTENT("BATCH_STATUS_INCONSISTENT"),
    SYSTEM_COMPANY_NOT_CONFIGURED("SYSTEM_COMPANY_NOT_CONFIGURED"),
    CONCURRENT_MODIFICATION("CONCURRENT_MODIFICATION"),
    CONFIG_INVALID("CONFIG_INVALID"),
    GENERATION_IDEMPOTENCY_CONFLICT("GENERATION_IDEMPOTENCY_CONFLICT"),
    EXCHANGE_IDEMPOTENCY_CONFLICT("EXCHANGE_IDEMPOTENCY_CONFLICT"),
    INSUFFICIENT_SERVICE_CODES("INSUFFICIENT_SERVICE_CODES"),
    EXCHANGE_STATE_INCONSISTENT("EXCHANGE_STATE_INCONSISTENT"),
    RENEWAL_IDEMPOTENCY_CONFLICT("RENEWAL_IDEMPOTENCY_CONFLICT"),
    ACCOUNT_RENEWAL_IN_PROGRESS("ACCOUNT_RENEWAL_IN_PROGRESS"),
    ACCOUNT_RENEWAL_STATE_INCONSISTENT("ACCOUNT_RENEWAL_STATE_INCONSISTENT"),
    GENERATION_ALREADY_EXISTS("GENERATION_ALREADY_EXISTS"),
    GENERATION_CONCURRENT_RETRY("GENERATION_CONCURRENT_RETRY"),
    OFFLINE_IMPORT_INVALID("OFFLINE_IMPORT_INVALID"),
    AUTHENTICATION_REQUIRED("AUTHENTICATION_REQUIRED"),
    UNSUPPORTED_USER_SCOPE("UNSUPPORTED_USER_SCOPE"),
    INTERNAL_ERROR("INTERNAL_ERROR");

    private final String value;

    ErrorCode(String value) {
        this.value = value;
    }

    public String value() {
        return value;
    }
}
