package com.sinognss.cloud.vantix.common.exception;

public enum ErrorCode {
    INVALID_ARGUMENT("INVALID_ARGUMENT"),
    NOT_FOUND("NOT_FOUND"),
    COMPANY_RELATION_INVALID("COMPANY_RELATION_INVALID"),
    SERVICE_CODE_EXPIRED("SERVICE_CODE_EXPIRED"),
    SERVICE_CODE_NOT_PENDING("SERVICE_CODE_NOT_PENDING"),
    SERVICE_CODE_NOT_OWNED("SERVICE_CODE_NOT_OWNED"),
    TRANSFER_NOT_ALLOWED("TRANSFER_NOT_ALLOWED"),
    BATCH_STATUS_INCONSISTENT("BATCH_STATUS_INCONSISTENT"),
    SYSTEM_COMPANY_NOT_CONFIGURED("SYSTEM_COMPANY_NOT_CONFIGURED"),
    CONCURRENT_MODIFICATION("CONCURRENT_MODIFICATION"),
    CONFIG_INVALID("CONFIG_INVALID"),
    INTERNAL_ERROR("INTERNAL_ERROR");

    private final String value;

    ErrorCode(String value) {
        this.value = value;
    }

    public String value() {
        return value;
    }
}
